version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"

